# Generated by Django 3.1.6 on 2021-06-24 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200, null=True)),
                ('age', models.IntegerField()),
                ('section', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('image', models.ImageField(blank=True, default='default.png', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.BooleanField(default=False, verbose_name='restlessness')),
                ('b', models.BooleanField(default=False, verbose_name='difficulty concentrating')),
                ('c', models.BooleanField(default=False, verbose_name='irritability')),
                ('d', models.BooleanField(default=False, verbose_name='dizziness')),
                ('e', models.BooleanField(default=False, verbose_name='tiredness')),
                ('f', models.BooleanField(default=False, verbose_name='feeling sick')),
                ('g', models.BooleanField(default=False, verbose_name='muscle aches')),
                ('h', models.BooleanField(default=False, verbose_name='a sense of dread')),
                ('i', models.BooleanField(default=False, verbose_name='headache')),
                ('j', models.BooleanField(default=False, verbose_name='insomnia')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='anxiety.respondent')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralizedAnxietyDisorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tupc_id', models.CharField(max_length=200, null=True)),
                ('points', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('anxiety_level', models.CharField(choices=[('Minimal', 'Minimal'), ('Mild', 'Mild'), ('Moderate', 'Moderate'), ('Severe', 'Severe')], max_length=200, null=True)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='anxiety.respondent')),
            ],
        ),
        migrations.CreateModel(
            name='BinaryLogisticRegression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('computer_or_laptop', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('Living_with_family', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('internet_connection', models.CharField(choices=[('Stable', 'Stable'), ('Unstable', 'Unstable')], max_length=200, null=True)),
                ('main_cause', models.CharField(blank="I don't Know", max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('anxiety', models.ManyToManyField(to='anxiety.GeneralizedAnxietyDisorder')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='anxiety.respondent')),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('EASE', 'EASE'), ('DIS-EASE', 'EASE')], max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('anxiety_levels', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='anxiety.generalizedanxietydisorder')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='anxiety.respondent')),
                ('predictors', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='anxiety.binarylogisticregression')),
            ],
        ),
    ]
